import type { FacilityZone } from '../../types/facility';

export const DEFAULT_HERO_ZONES: FacilityZone[] = [
  {
    id: 'wellhead-area',
    name: 'Wellhead Christmas Tree Area',
    code: 'Z-01',
    description: 'High-pressure extraction manifolds and hydraulic emergency shutdown valves',
    risk_score: 78,
    risk_level: 'HIGH',
    total_incidents: 14,
    active_incidents: 2,
    critical_incidents: 3,
    recent_incident_state: true,
    risk_trend: 'INCREASE',
    risk_trend_delta: 6,
    risk_factors: [{ title: 'Pressure differential', impact: 'High', description: 'Flange micro-leak detected on manifold', category: 'sif_precursor' }],
    dominant_hazard: 'High Pressure Gas Release',
    recommended_actions: ['Isolate valve bank', 'Inspect flange gaskets'],
    incidents: [],
    svg_center: { x: 120, y: 140 },
  },
  {
    id: 'pump-station',
    name: 'Main Pump & Compressor Station',
    code: 'Z-02',
    description: 'Heavy centrifugal booster pumps and crude transmission manifolds',
    risk_score: 84,
    risk_level: 'CRITICAL',
    total_incidents: 22,
    active_incidents: 4,
    critical_incidents: 5,
    recent_incident_state: true,
    risk_trend: 'INCREASE',
    risk_trend_delta: 9,
    risk_factors: [{ title: 'Vibration anomaly', impact: 'Critical', description: 'Compressor bearing overheating', category: 'sif_precursor' }],
    dominant_hazard: 'Mechanical Failure & Thermal Energy',
    recommended_actions: ['Vibration frequency analysis', 'Lubrication flush'],
    incidents: [],
    svg_center: { x: 300, y: 140 },
  },
  {
    id: 'tank-farm',
    name: 'Hydrocarbon Storage Tank Farm',
    code: 'Z-03',
    description: 'Floating roof crude storage tanks and secondary bund retention barriers',
    risk_score: 52,
    risk_level: 'MODERATE',
    total_incidents: 9,
    active_incidents: 1,
    critical_incidents: 1,
    recent_incident_state: false,
    risk_trend: 'STABLE',
    risk_trend_delta: 0,
    risk_factors: [{ title: 'Level sensor drift', impact: 'Moderate', description: 'Secondary radar gauge calibration required', category: 'barrier_breach' }],
    dominant_hazard: 'Vapor Flammability',
    recommended_actions: ['Calibrate level sensors', 'Check seal integrity'],
    incidents: [],
    svg_center: { x: 480, y: 140 },
  },
  {
    id: 'pipeline-corridor',
    name: 'Main Multi-Tier Pipeline Corridor',
    code: 'Z-04',
    description: 'Interconnecting crude, gas, and steam rack arteries across facility',
    risk_score: 41,
    risk_level: 'LOW',
    total_incidents: 6,
    active_incidents: 0,
    critical_incidents: 0,
    recent_incident_state: false,
    risk_trend: 'DECREASE',
    risk_trend_delta: -3,
    risk_factors: [{ title: 'Expansion joint wear', impact: 'Low', description: 'Scheduled ultrasonic wall thickness gauge', category: 'baseline' }],
    dominant_hazard: 'Corrosion Under Insulation',
    recommended_actions: ['Routine NDT survey'],
    incidents: [],
    svg_center: { x: 300, y: 260 },
  },
  {
    id: 'control-room',
    name: 'Central SCADA & SIS Control Hub',
    code: 'Z-05',
    description: 'Dual-redundant safety instrumented system racks and operator consoles',
    risk_score: 18,
    risk_level: 'LOW',
    total_incidents: 2,
    active_incidents: 0,
    critical_incidents: 0,
    recent_incident_state: false,
    risk_trend: 'STABLE',
    risk_trend_delta: 0,
    risk_factors: [{ title: 'UPS Battery Cycle', impact: 'Low', description: 'Routine power switchover verification', category: 'baseline' }],
    dominant_hazard: 'Electrical Inverter Tripping',
    recommended_actions: ['Normal monitoring'],
    incidents: [],
    svg_center: { x: 120, y: 380 },
  },
  {
    id: 'maintenance-area',
    name: 'Mechanical Workshop & Crane Bay',
    code: 'Z-06',
    description: 'Rotating equipment overhaul bays and overhead crane rigging area',
    risk_score: 65,
    risk_level: 'MODERATE',
    total_incidents: 16,
    active_incidents: 2,
    critical_incidents: 2,
    recent_incident_state: false,
    risk_trend: 'DECREASE',
    risk_trend_delta: -4,
    risk_factors: [{ title: 'Overhead Rigging Inspection', impact: 'Moderate', description: 'Tag-out overdue on auxiliary hoist line', category: 'barrier_breach' }],
    dominant_hazard: 'Suspended Loads',
    recommended_actions: ['Re-certify crane slings', 'Enforce exclusion zone'],
    incidents: [],
    svg_center: { x: 300, y: 380 },
  },
  {
    id: 'loading-area',
    name: 'Road Tanker Gantry Terminal',
    code: 'Z-07',
    description: 'Automated bottom-loading arms with vapor recovery and earth grounding',
    risk_score: 72,
    risk_level: 'HIGH',
    total_incidents: 11,
    active_incidents: 2,
    critical_incidents: 2,
    recent_incident_state: true,
    risk_trend: 'INCREASE',
    risk_trend_delta: 5,
    risk_factors: [{ title: 'Earthing Interlock Override', impact: 'High', description: 'Static grounding interlock reported erratic reading', category: 'sif_precursor' }],
    dominant_hazard: 'Static Sparking in Hydrocarbon Atmosphere',
    recommended_actions: ['Replace grounding clamp cable', 'Verify interlock cut-off'],
    incidents: [],
    svg_center: { x: 480, y: 380 },
  },
];
